### ISSUE TITLE
_editorconfig instead of .editorconfig

### ISSUE THREAD

**Issue by stefanwalther** [generate/generate-editorconfig#2]
If you have a ~/template/_editorconfig defined, this will not be picked up properly (still don't understand which code-piece is doing that - any hint would be helpful), but stored as `_editorconfig` instead of `.editorconfig`.

**Comment by jonschlinkert** [comment]
I fixed this earlier today (I hope). Try installing generate 0.10.0 and the global generators. If that doesn't work I can push up a patch pretty quickly

**Comment by stefanwalther** [comment]
I have updated (a few mins before I was writing the post) all generators + generate + update + everything ;-)

![image](https://cloud.githubusercontent.com/assets/669728/17533049/7d4cdc94-5e83-11e6-8d0e-8588b2c0afd1.png)

**Comment by stefanwalther** [comment]
BTW: Can you point me pls to the piece of code where the default location ~/template/... is handled, thx.

**Comment by doowb** [comment]
@stefanwalther the location is currently handled in `generate` [here](https://github.com/generate/generate/blob/master/lib/mixins.js#L59-L67).

Some middleware that was registered by default in `generate` was externalized because it was also in `generate-defaults`. One of the middleware was handling stripping/changing the `_` and `$` prefixes from the template basename.

`generate-editorconfig` just needs to be updated to use `generate-defaults`. I've updated this locally and the template is using the correct name. I have not tested the user defined templates path yet. If you add `app.use(require('generate-defaults'));` to the [generator here](https://github.com/generate/generate-editorconfig/blob/master/generator.js#L8) (and make sure to `npm install generate-defaults`), does this work with your user defined templates?

If so, I can push up the changes I have.

**Comment by jonschlinkert** [comment]
@stefanwalther was this resolved for you?
