### ISSUE TITLE
Error running the generator

### ISSUE THREAD

**Issue by Jesus-Gonzalez** [generate/generate-editorconfig#3]
Hello,

When trying to run the generator, I get a persistent error message. I've pasted the error below.
I have tried running the generator from a NPM project directory and a regular directory.

I've installed the generator using the following command, and it installed properly:
```
13:00 $ sudo yarn global add generate-editorconfig generate
yarn global v1.3.2
warning package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
```

Software installed:
```
13:05 $ node --version
v8.9.4

13:07 $ npm --version
5.6.0

13:07 $ yarn --version
1.3.2

Operating System: Linux (Fedora 27)
```

Error:
```
13:05 $ gen editorconfig
[13:05:48] starting generate
[13:05:48] ✔ running tasks: [ 'editorconfig' ]
Error: Cannot find generator: "editorconfig" in "/home/jesus/projects/new-project"
    at Generate.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/base-generators/index.js:499:18)
    at iterate (/usr/local/share/.config/yarn/global/node_modules/async-each-series/index.js:8:5)
    at Function.module.exports (/usr/local/share/.config/yarn/global/node_modules/async-each-series/index.js:20:3)
    at Generate.generate (/usr/local/share/.config/yarn/global/node_modules/base-generators/index.js:492:15)
    at /usr/local/share/.config/yarn/global/node_modules/base-generators/index.js:475:18
    at iterate (/usr/local/share/.config/yarn/global/node_modules/async-each-series/index.js:8:5)
    at Function.module.exports (/usr/local/share/.config/yarn/global/node_modules/async-each-series/index.js:20:3)
    at Generate.generate (/usr/local/share/.config/yarn/global/node_modules/base-generators/index.js:474:24)
    at Generate.generate (/usr/local/share/.config/yarn/global/node_modules/base-generators/index.js:463:23)
    at /usr/local/share/.config/yarn/global/node_modules/generate/bin/generate.js:117:11
```

**Comment by doowb** [comment]
Hi @Jesus-Gonzalez 

Will you try installing the generator globally using `npm` and let me know if that works?

```sh
$ npm i -g generate-editorconfig
```

You can also use `yarn` and install the generator locally as a devDependency

**Comment by Jesus-Gonzalez** [comment]
Hello.

Installing `generate-editorconfig` with `npm` worked just fine.

Thanks :slightly_smiling_face:

**Comment by jonschlinkert** [comment]
Sounds like this was resolved, I'm going to go ahead and close. Thanks for creating the issue @Jesus-Gonzalez

**Comment by gwennlbh** [comment]
Doing `pnpm i -g generate-editorconfig` does not work either. I suggest that you highlight this in the documentation, since people that use package managers other than `npm` will not understand why it fails. I first I thought that I had to install it in the project's directory (without `-g`) and since the project is not in nodejs, I was about to give up before searching for this issue.

Add a "**NOTICE: Using `yarn` or `pnpm` instead will _not_ work**" in the installation part of the readme, it'll help people out 😉

**Comment by jonschlinkert** [comment]
The documentation currently shows `npm`, I don't think it mentions other package managers. I think it makes more sense to add documentation for things we support, not for things we don't support. 

FWIW, I'm releasing a new version soon and will ensure that it works with yarn, npx, and hopefully pnpm (I haven't used it yet). Please [open issues](https://github.com/generate/generate/issues/new) to add any others. Thanks.

**Comment by gwennlbh** [comment]
Of course, you show npm in the docs because that's the standard, default one that everyone shows. Every documentation of every library shows npm. 

But the usual behavior is that doing `yarn add` or `pnpm i` instead of `npm i` will work without any hiccup.

What your lib does is not usual behavior, and thus needs to be documented.

In a perfect world, yes, you only document what you support. But remember, documentation is meant for humans, so _context_ is crucial. In the JS ecosystem, one piece of context is that there are other package managers that work transparently when installing any lib or CLI, globally or not. Yours does not (for now!), so it's worth adding a little line in your README, because some people will search for issues, some will just give up for various reasons.

> FWIW, I'm releasing a new version soon and will ensure that it works with yarn, npx, and hopefully pnpm 

Nice!
